language: cpp
sudo: required
dist: trusty
before_install:
- source travis-scripts/install-clutils.sh
- source travis-scripts/install-savant.sh
- source travis-scripts/setup-autotools.sh
script: source travis-scripts/build.sh
